#!/bin/sh
#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

insmod /lib/modules/4.9.275/kernel/drivers/vmm/signal.ko
insmod /lib/modules/4.9.275/kernel/drivers/vmm/poison.ko
