#!/bin/sh
#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

insmod /lib/modules/4.9.307/kernel/drivers/vmm/connection.ko
insmod /lib/modules/4.9.307/kernel/drivers/vmm/poison.ko
# insmod /lib/modules/4.9.307/kernel/drivers/vmm/signal.ko

export CML_STACK_SIZE=10
export CML_HEAP_SIZE=10

/useram/useram
