#!/bin/sh
#
# Copyright 2019, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

# a sample module to detect via introspection
insmod /lib/modules/4.9.307/kernel/drivers/vmm/poison.ko

# the module which allows communication to the platform AM
insmod /lib/modules/4.9.307/kernel/drivers/vmm/connection.ko

# Configure useram user/group and permissions
addgroup -S useram
adduser -DSH -s /bin/false -G useram -g useram useram
chown -R useram:useram /useram
chown useram:useram /dev/uio*

chmod u=srx /useram/useram
chmod g=s   /useram/useram
chmod o=    /useram/useram

export CML_STACK_SIZE=10
export CML_HEAP_SIZE=10

# Run useram daemon
/useram/useram

# Configure attarch user/group
addgroup attarch
mkdir -p /home/attarch
adduser -D -s /bin/sh -h /home/attarch -G attarch -g attarch attarch
passwd -d attarch#!/bin/sh



